# Generated by Django 3.2 on 2021-04-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='option',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='option',
            name='status',
        ),
    ]
