# Generated by Django 3.2 on 2021-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_site', '0002_auto_20210430_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avantage',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='carde',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='image',
            name='cadre',
        ),
        migrations.DeleteModel(
            name='Pattners',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Avantage',
        ),
        migrations.DeleteModel(
            name='Carde',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
